#自定义配置信息
version: 1.0.0
#自定义启动端口
server:
  port: 8081
person:
  name: 胡丁文
  age: 20
  address: [北京,上海,广东,深圳]
  address2:
    - 北京
    - 上海
    - 广东
    - 深圳

spring:
  #redis相关配置
  redis:
    host: 127.0.0.1
    port: 6379
  #数据库相关配置
  datasource:
    url: jdbc:dm://192.168.0.70:5236?LobMode=1&schema=LIMS
    username: SYSDBA
    password: SYSDBA001
    driver-class-name: dm.jdbc.driver.DmDriver
    type: com.alibaba.druid.pool.DruidDataSource
  #quartz定时任务相关配置
  quartz:
    job-store-type: memory # Job 存储器类型。默认为 memory 表示内存，可选 jdbc 使用数据库。
    auto-startup: true # Quartz 是否自动启动
    startup-delay: 0 # 延迟 N 秒启动
    wait-for-jobs-to-complete-on-shutdown: true # 应用关闭时，是否等待定时任务执行完成。默认为 false ，建议设置为 true
    overwrite-existing-jobs: false # 是否覆盖已有 Job 的配置
    properties: # 添加 Quartz Scheduler 附加属性
      org:
        quartz:
          threadPool:
            threadCount: 25 # 线程池大小。默认为 10 。
            threadPriority: 5 # 线程优先级
            class: org.quartz.simpl.SimpleThreadPool # 线程池类型
#mybatis相关配置
mybatis:
  #配置读取xml路径
#  mapper-locations: classpath:mapper/*.xml
  #配置实体别名
#  type-aliases-package: com.hudingwen.springboot.entity
mybatis-plus:
  #配置读取xml路径
  mapper-locations: classpath:mapper/*.xml
  #配置实体别名
  type-aliases-package: com.hudingwen.springboot.entity
  global-config:
    db-column-underline: true  #开启驼峰转换
    db-config:
      id-type: assign_uuid
      field-strategy: not_null
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句便于调试
#pagehelper配置
pagehelper:
  auto-dialect: true
  close-conn: true
  offset-as-page-num: true

